# Generated by Django 2.1.4 on 2019-01-07 22:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obelezje', models.CharField(max_length=200)),
                ('cena', models.PositiveIntegerField()),
                ('opis', models.TextField(blank=True)),
                ('photo1', models.ImageField(blank=True, default='no_photo.png', upload_to='cars/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, default='no_photo.png', upload_to='cars/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, default='no_photo.png', upload_to='cars/%Y/%m/%d')),
                ('photo4', models.ImageField(blank=True, default='no_photo.png', upload_to='cars/%Y/%m/%d')),
                ('photo5', models.ImageField(blank=True, default='no_photo.png', upload_to='cars/%Y/%m/%d')),
                ('photo6', models.ImageField(blank=True, default='no_photo.png', upload_to='cars/%Y/%m/%d')),
                ('photo7', models.ImageField(blank=True, default='no_photo.png', upload_to='cars/%Y/%m/%d')),
                ('photo8', models.ImageField(blank=True, default='no_photo.png', upload_to='cars/%Y/%m/%d')),
                ('oglas_postavljen', models.DateTimeField(default=datetime.datetime.now)),
                ('godiste', models.PositiveIntegerField()),
                ('karoserija', models.CharField(choices=[('Limuzina', 'Limuzina'), ('Hečbek', 'Hečbek'), ('Karavan', 'Karavan'), ('Kupe', 'Kupe'), ('Monovolumen', 'Monovolumen'), ('Kabriolet', 'Kabriolet')], max_length=200)),
                ('gorivo', models.CharField(choices=[('Dizel', 'Dizel'), ('Benzin', 'Benzin'), ('Benzin + TNG', 'Benzin + TNG'), ('Metan CNG', 'Metan CNG'), ('Hibrid', 'Hibrid')], max_length=200)),
                ('kubikaza', models.PositiveIntegerField()),
                ('snaga_kw', models.PositiveIntegerField()),
                ('kilometraza', models.PositiveIntegerField()),
                ('broj_vrata', models.CharField(choices=[('2/3', '2/3'), ('4/5', '4/5')], max_length=200)),
                ('broj_sedista', models.CharField(choices=[('2 sedista', '2 sedista'), ('3 sedista', '3 sedista'), ('4 sedista', '4 sedista'), ('5 sedista', '5 sedista'), ('6 sedista', '6 sedista'), ('7 sedista', '7 sedista'), ('8 sedista', '8 sedista')], max_length=200)),
                ('menjac', models.CharField(choices=[('Manuelni 4 brzine', 'Manuelni 4 brzine'), ('Manuelni 5 brzina', 'Manuelni 5 brzina'), ('Manuelni 6 brzina', 'Manuelni 6 brzina'), ('Poluautomatski', 'Poluautomatski'), ('Automatski', 'Automatski')], max_length=200)),
                ('boja', models.CharField(max_length=100)),
                ('klima', models.CharField(choices=[('Nema klimu', 'Nema klimu'), ('Manuelna klima', 'Manuelna klima'), ('Automatska klima', 'Automatska klima')], max_length=100)),
                ('registrovan_do', models.DateField()),
                ('abs', models.BooleanField(default=False)),
                ('esp', models.BooleanField(default=False)),
                ('airbag_vozac', models.BooleanField(default=False)),
                ('airbag_suvozac', models.BooleanField(default=False)),
                ('alarm', models.BooleanField(default=False)),
                ('centralno_zakljucavanje', models.BooleanField(default=False)),
                ('tempomat', models.BooleanField(default=False)),
                ('putni_racunar', models.BooleanField(default=False)),
                ('metalik_boja', models.BooleanField(default=False)),
                ('navigacija', models.BooleanField(default=False)),
                ('svetla_za_maglu', models.BooleanField(default=False)),
                ('siber', models.BooleanField(default=False)),
                ('alu_felne', models.BooleanField(default=False)),
                ('dpf', models.BooleanField(default=False)),
                ('kuka', models.BooleanField(default=False)),
                ('kamera', models.BooleanField(default=False)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
