# Generated by Django 2.1.4 on 2018-12-24 13:16

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mesto', models.CharField(max_length=200)),
                ('postanski_broj', models.PositiveIntegerField()),
                ('adresa', models.CharField(max_length=200)),
                ('telefon', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obelezje', models.CharField(max_length=200)),
                ('cena', models.PositiveIntegerField()),
                ('opis', models.TextField(blank=True)),
                ('photo1', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('photo4', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('photo5', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('photo6', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('photo7', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('photo8', models.ImageField(blank=True, upload_to='cars/%Y/%m/%d')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('godiste', models.PositiveIntegerField()),
                ('karoserija', models.CharField(max_length=200)),
                ('gorivo', models.CharField(max_length=200)),
                ('kubikaza', models.PositiveIntegerField()),
                ('snaga_kw', models.PositiveIntegerField()),
                ('kilometraza', models.PositiveIntegerField()),
                ('broj_vrata', models.PositiveIntegerField()),
                ('broj_sedista', models.PositiveIntegerField()),
                ('menjac', models.CharField(max_length=100)),
                ('boja', models.CharField(max_length=100)),
                ('klima', models.CharField(max_length=100)),
                ('registrovan_do', models.DateField()),
                ('abs', models.BooleanField(default=False)),
                ('esp', models.BooleanField(default=False)),
                ('airbag_vozac', models.BooleanField(default=False)),
                ('airbag_suvozac', models.BooleanField(default=False)),
                ('alarm', models.BooleanField(default=False)),
                ('centralno_zakljucavanje', models.BooleanField(default=False)),
                ('tempomat', models.BooleanField(default=False)),
                ('putni_racunar', models.BooleanField(default=False)),
                ('metalik_boja', models.BooleanField(default=False)),
                ('navigacija', models.BooleanField(default=False)),
                ('svetla_za_maglu', models.BooleanField(default=False)),
                ('siber', models.BooleanField(default=False)),
                ('alu_felne', models.BooleanField(default=False)),
                ('dpf', models.BooleanField(default=False)),
                ('kuka', models.BooleanField(default=False)),
                ('kamera', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
