# Generated by Django 2.1.4 on 2018-12-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20181225_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
