# Generated by Django 2.1.4 on 2018-12-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20181225_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Brand'),
        ),
    ]
