# Generated by Django 2.1.4 on 2018-12-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_fleet_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='karoserija',
            field=models.CharField(choices=[('Limuzina', 'Limuzina'), ('Hečbek', 'Hečbek'), ('Karavan', 'Karavan'), ('Kupe', 'Kupe'), ('Monovolumen', 'Monovolumen'), ('Kabriolet', 'Kabriolet')], max_length=200),
        ),
    ]
