# Generated by Django 2.1.4 on 2018-12-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20181227_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='broj_sedista',
            field=models.CharField(choices=[('2 sedista', '2 sedista'), ('3 sedista', '3 sedista'), ('4 sedista', '4 sedista'), ('5 sedista', '5 sedista'), ('6 sedista', '6 sedista'), ('7 sedista', '7 sedista'), ('8 sedista', '8 sedista')], max_length=200),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='klima',
            field=models.CharField(choices=[('Nema klimu', 'Nema klimu'), ('Manuelna klima', 'Manuelna klima'), ('Automatska klima', 'Automatska klima')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='menjac',
            field=models.CharField(choices=[('Manuelni 4 brzine', 'Manuelni 4 brzine'), ('Manuelni 5 brzina', 'Manuelni 5 brzina'), ('Manuelni 6 brzina', 'Manuelni 6 brzina'), ('Poluautomatski', 'Poluautomatski'), ('Automatski', 'Automatski')], max_length=200),
        ),
    ]
