# Generated by Django 2.1.4 on 2018-12-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20181227_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='date',
            new_name='oglas_postavljen',
        ),
    ]
