# Generated by Django 2.1.4 on 2018-12-29 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20181227_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='oglas_postavljen',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
