# Generated by Django 2.1.4 on 2018-12-29 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20181229_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='oglas_postavljen',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
